#!/usr/bin/env python3
"""AEGIS docgen (Python edition) — deterministic docs from the Ariadne graph.
Zero LLM tokens. Outputs docs/generated/: architecture.md, message-flows.md,
data-map.md, PROGRESS.md, agent-context.md. Run from workspace/repo root."""
import json
import os
import re
import sqlite3
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path.cwd()
DB = Path(os.environ.get("ARIADNE_HOME", ROOT)) / ".ariadne" / "index.db"
OUT = ROOT / "docs" / "generated"
FEATURES = ROOT / "docs" / "features"
STAMP = f"<!-- generated by aegis docgen {datetime.now(timezone.utc).isoformat()} — do not edit by hand -->"

try:
    _dcfg = json.loads((DB.parent / "config.json").read_text())
except Exception:  # noqa: BLE001
    _dcfg = {}
MAX_DIAGRAM_NODES = _dcfg.get("maxDiagramNodes", 30)
MAX_DOC_ITEMS = _dcfg.get("maxDocItems", 60)


def big_doc_banner(count, what, tool):
    if count <= MAX_DOC_ITEMS:
        return ""
    return (f"> **This file describes {count} {what}.** Do not read it whole into an agent's context —\n"
            f"> query `{tool}` for the one you need. The warnings below are the part worth reading.\n\n")

if not DB.exists():
    sys.exit("Index not found — run the Ariadne indexer first.")
OUT.mkdir(parents=True, exist_ok=True)
con = sqlite3.connect(f"file:{DB}?mode=ro", uri=True)
con.row_factory = sqlite3.Row
q = lambda sql, *a: con.execute(sql, a).fetchall()
svc = lambda p: p.split("/")[0]
mm = lambda s: re.sub(r"[^\w]", "_", s)


def write(name, body):
    (OUT / name).write_text(f"{STAMP}\n\n{body}")
    print("  +", f"docs/generated/{name}")


# architecture
files = q("SELECT path, lang FROM files")
services = {}
for f in files:
    s = services.setdefault(svc(f["path"]), {"files": 0, "langs": {}})
    s["files"] += 1
    s["langs"][f["lang"]] = s["langs"].get(f["lang"], 0) + 1
edges = q("SELECT DISTINCT f1.path a, f2.path b FROM edges e JOIN files f1 ON f1.id=e.src JOIN files f2 ON f2.id=e.dst")
svc_edges = {f"{svc(e['a'])}-->{svc(e['b'])}" for e in edges if svc(e["a"]) != svc(e["b"])}
hot = q("SELECT f.path, COUNT(e.src) n FROM files f JOIN edges e ON e.dst=f.id GROUP BY f.id ORDER BY n DESC LIMIT 10")
md = "# System Architecture (generated)\n\n## Modules\n\n| Module | Files | Main languages |\n|---|---|---|\n"
for name in sorted(services):
    s = services[name]
    langs = ", ".join(sorted(s["langs"], key=s["langs"].get, reverse=True)[:3])
    md += f"| {name} | {s['files']} | {langs} |\n"
shown = sorted(services.items(), key=lambda kv: -kv[1]["files"])[:MAX_DIAGRAM_NODES]
shown_names = {n for n, _ in shown}
md += "\n## Module dependency map\n\n"
if len(services) > MAX_DIAGRAM_NODES:
    md += (f"_Showing the {MAX_DIAGRAM_NODES} largest of {len(services)} modules — a diagram with every "
           "node is unreadable. Full list in the table above._\n\n")
md += "```mermaid\nflowchart LR\n"
for name, _ in shown:
    md += f'  {mm(name)}["{name}"]\n'
for e in svc_edges:
    a, b = e.split("-->")
    if a not in shown_names or b not in shown_names:
        continue
    md += f"  {mm(a)} --> {mm(b)}\n"
md += "```\n\n## Most-depended-on files (change with care)\n\n"
md += "".join(f"- `{h['path']}` — {h['n']} dependents\n" for h in hot)
write("architecture.md", md)

# message flows
rows = q("SELECT m.topic, m.direction, f.path, m.line, m.via FROM msg_edges m JOIN files f ON f.id=m.file_id ORDER BY m.topic")
md = "# Kafka Message Flows (generated)\n\n" + big_doc_banner(len({r["topic"] for r in rows}), "topics", "message_flow topic:<name>")
if not rows:
    md += "_No Kafka producers/consumers detected._\n"
else:
    topics = {}
    for r in rows:
        topics.setdefault(r["topic"], []).append(r)
    md += "```mermaid\nflowchart LR\n"
    seen = set()
    for topic, hs in topics.items():
        t = f"T_{mm(topic)}"
        md += f'  {t}(["{topic}"]):::topic\n'
        for h in hs:
            s = mm(svc(h["path"]))
            if s not in seen:
                md += f'  {s}["{svc(h["path"])}"]\n'
                seen.add(s)
            md += (f"  {s} -->|publish| {t}\n" if h["direction"] == "produce" else f"  {t} -->|consume| {s}\n")
    md += "  classDef topic fill:#1e3a5f,color:#e8c468,stroke:#c9962e\n```\n\n## Per-topic detail\n\n"
    for topic, hs in topics.items():
        md += f"### `{topic}`\n"
        prod = [h for h in hs if h["direction"] == "produce"]
        cons = [h for h in hs if h["direction"] == "consume"]
        for h in hs:
            via = f" (via `{h['via']}`)" if h["via"] else ""
            md += f"- **{'publish' if h['direction']=='produce' else 'consume'}** — `{h['path']}:{h['line']}`{via}\n"
        if prod and not cons:
            md += "- ⚠️ produced but no consumer found in the indexed workspace\n"
        if cons and not prod:
            md += "- ⚠️ consumed but no producer found in the indexed workspace\n"
        md += "\n"
write("message-flows.md", md)

# data map
defs = q("SELECT d.tbl, d.op, f.path, d.line, d.changeset FROM db_defs d LEFT JOIN files f ON f.id=d.file_id ORDER BY d.tbl")
accs = q("SELECT a.tbl, a.kind, a.mode, f.path, a.line, a.detail FROM db_access a JOIN files f ON f.id=a.file_id ORDER BY a.tbl")
md = "# Data Map — tables, services, changesets (generated)\n\n" + big_doc_banner(len({d["tbl"] for d in defs} | {a["tbl"] for a in accs}), "tables", "db_map table:<name>")
if not defs and not accs:
    md += "_No Liquibase changelogs or DB access detected._\n"
else:
    tables = {}
    for d in defs:
        tables.setdefault(d["tbl"], {"defs": [], "accs": []})["defs"].append(d)
    for a in accs:
        tables.setdefault(a["tbl"], {"defs": [], "accs": []})["accs"].append(a)
    md += "```mermaid\nflowchart LR\n"
    seen = set()
    for tbl, t in tables.items():
        md += f'  DB_{mm(tbl)}[("{tbl}")]:::tbl\n'
        for a in t["accs"]:
            s = mm(svc(a["path"]))
            if s not in seen:
                md += f'  {s}["{svc(a["path"])}"]\n'
                seen.add(s)
            md += f"  {s} -->|{a['mode']}| DB_{mm(tbl)}\n"
    md += "  classDef tbl fill:#0d1b2e,color:#7dd3fc,stroke:#38bdf8\n```\n\n## Per-table detail\n\n"
    for tbl in sorted(tables):
        t = tables[tbl]
        md += f"### `{tbl}`\n"
        if t["defs"]:
            md += "**Schema history:** " + " → ".join(f"{d['op']}{' ['+d['changeset']+']' if d['changeset'] else ''}" for d in t["defs"]) + "\n"
            md += "".join(f"- {d['op']} @ `{d['path']}:{d['line']}`\n" for d in t["defs"])
        else:
            md += "- ⚠️ **DRIFT** — accessed by code but no Liquibase changeset defines it in the indexed workspace\n"
        md += "".join(f"- {a['kind']} [{a['mode']}] — `{a['path']}:{a['line']}` ({a['detail']})\n" for a in t["accs"])
        if t["defs"] and not t["accs"]:
            md += "- ⚠️ defined in changelog but no code access found\n"
        md += "\n"
write("data-map.md", md)

# http map
from http_extract import paths_match
eps = q("SELECT e.method, e.path, e.norm, f.path fp, e.line FROM http_endpoints e JOIN files f ON f.id=e.file_id ORDER BY e.norm")
hcalls = q("SELECT c.method, c.path, c.norm, f.path fp, c.line, c.client FROM http_calls c JOIN files f ON f.id=c.file_id")
md = "# HTTP Seam — endpoints and callers (generated)\n\n" + big_doc_banner(len(eps), "endpoints", "http_map path:<fragment>")
if not eps and not hcalls:
    md += "_No REST endpoints or HTTP clients detected._\n"
else:
    md += "```mermaid\nflowchart LR\n"
    seen, matched = set(), set()
    for e in eps:
        es = mm(svc(e["fp"]))
        if es not in seen:
            md += f'  {es}["{svc(e["fp"])}"]\n'; seen.add(es)
        for i, c in enumerate(hcalls):
            if c["method"] == e["method"] and paths_match(c["norm"], e["norm"]):
                matched.add(i)
                cs = mm(svc(c["fp"]))
                if cs not in seen:
                    md += f'  {cs}["{svc(c["fp"])}"]\n'; seen.add(cs)
                md += f'  {cs} -->|"{e["method"]} {e["norm"]}"| {es}\n'
    md += "```\n\n## Endpoints\n\n"
    for e in eps:
        callers = [c for c in hcalls if c["method"] == e["method"] and paths_match(c["norm"], e["norm"])]
        md += f"- **{e['method']} {e['path']}** — `{e['fp']}:{e['line']}`"
        md += ("\n" + "\n".join(f"  - caller: `{c['fp']}:{c['line']}` ({c['client']})" for c in callers)
               if callers else " — ⚠️ no caller found in the indexed workspace") + "\n"
    un = [c for i, c in enumerate(hcalls) if i not in matched]
    if un:
        md += "\n## Unmatched outbound calls (external APIs or dynamic paths)\n\n"
        md += "\n".join(f"- {c['method']} {c['path']} — `{c['fp']}:{c['line']}` ({c['client']})" for c in un) + "\n"
write("http-map.md", md)

# decisions
has_dec = bool(q("SELECT name FROM sqlite_master WHERE name='decisions'"))
rows = q("SELECT * FROM decisions ORDER BY decided_at DESC") if has_dec else []
md = "# Decision Memory — Mnemosyne (generated)\n\n"
if not rows:
    md += "_No ADR decisions found. Capture one in chat via the save_decision tool, or add docs/adr/ADR-NNN-*.md files._\n"
else:
    active = [r for r in rows if not r["valid_until"]]
    md += f"## Active decisions ({len(active)})\n\n| ID | Title | Decided | Governs |\n|---|---|---|---|\n"
    for r in active:
        g = q("SELECT kind, target FROM decision_links WHERE decision_id=?", r["id"])
        md += f"| {r['id']} | {r['title']} | {r['decided_at'] or '?'} | {', '.join(l['kind'] + ':' + l['target'] for l in g) or '—'} |\n"
    sup = [r for r in rows if r["valid_until"]]
    if sup:
        md += "\n## Superseded (history preserved)\n\n"
        for r in sup:
            md += f"- ~~{r['id']}: {r['title']}~~ — valid {r['decided_at']} → {r['valid_until']}, superseded by **{r['superseded_by']}**\n"
    md += "\n_Query in chat: decisions / decision_trace; time-travel with as_of. Capture new ones with save_decision._\n"
write("decisions.md", md)

# progress
md = "# Progress Report (generated)\n\n"
feats = sorted([d for d in FEATURES.iterdir() if d.is_dir()]) if FEATURES.exists() else []
if not feats:
    md += "_No feature artifacts under docs/features/ yet. Features managed via the spec-driven-artifacts skill will appear here automatically._\n"
else:
    g = {"done": 0, "prog": 0, "blocked": 0, "todo": 0}
    rows_out = []
    for f in feats:
        rd = lambda n: (f / n).read_text() if (f / n).exists() else ""
        tasks = rd("tasks.md")
        c = {"done": len(re.findall(r"^- \[x\]", tasks, re.I | re.M)),
             "prog": len(re.findall(r"^- \[~\]", tasks, re.M)),
             "blocked": len(re.findall(r"^- \[!\]", tasks, re.M)),
             "todo": len(re.findall(r"^- \[ \]", tasks, re.M))}
        total = sum(c.values())
        for k in g:
            g[k] += c[k]
        frs = len(re.findall(r"^\s*-\s*\*\*FR-", rd("spec.md"), re.I | re.M))
        clar = len(re.findall(r"NEEDS CLARIFICATION", rd("spec.md")))
        verdicts = re.findall(r"\*\*Verdict\*\*:\s*([A-Z-]+)", rd("review.md"))
        pct = round(c["done"] / total * 100) if total else 0
        status = "🔴 blocked" if c["blocked"] else "✅ done" if pct == 100 else "🟡 in progress" if (c["prog"] or c["done"]) else "⚪ not started"
        rows_out.append(f"| {f.name} | {status} | {pct}% | {c['done']}/{total} | {frs} | {clar or '—'} | {verdicts[-1] if verdicts else '—'} |")
    gt = sum(g.values())
    md += f"**Overall: {round(g['done']/gt*100) if gt else 0}% of tracked tasks complete** ({g['done']} done, {g['prog']} in progress, {g['blocked']} blocked, {g['todo']} to do)\n\n"
    md += "```mermaid\npie showData\n  title Task status across all features\n"
    md += f'  "Done" : {g["done"]}\n  "In progress" : {g["prog"]}\n  "Blocked" : {g["blocked"]}\n  "To do" : {g["todo"]}\n```\n\n'
    md += "| Feature | Status | % | Tasks | FRs | Open clarifications | Last review |\n|---|---|---|---|---|---|---|\n"
    md += "\n".join(rows_out) + "\n\n_Counts derive from docs/features/*/tasks.md checkboxes, spec.md FR-### lines, and review.md verdicts._\n"
write("PROGRESS.md", md)

# agent context
services_l = sorted({svc(f["path"]) for f in files})
topics_l = [r["topic"] for r in q("SELECT DISTINCT topic FROM msg_edges ORDER BY topic")]
tables_l = [r[0] for r in q("SELECT DISTINCT tbl FROM db_defs UNION SELECT DISTINCT tbl FROM db_access ORDER BY 1")]
hot6 = q("SELECT f.path, COUNT(e.src) n FROM files f JOIN edges e ON e.dst=f.id GROUP BY f.id ORDER BY n DESC LIMIT 6")
sym = q("SELECT COUNT(*) c FROM symbols")[0]["c"]
top_topics = [r[0] for r in q("SELECT topic, COUNT(*) n FROM msg_edges GROUP BY topic ORDER BY n DESC LIMIT 15")]
top_tables = [r[0] for r in q("SELECT tbl, COUNT(*) n FROM db_access GROUP BY tbl ORDER BY n DESC LIMIT 15")]
_more = lambda all_, n, doc: f" (+{len(all_) - n} more — see {doc})" if len(all_) > n else ""  # noqa: E731
md = f"""# Agent Context Pack (generated — read this FIRST, then use Ariadne tools)

This file plus one or two tool calls should orient you completely. Do not
re-derive anything listed here by reading source files. This pack is deliberately
bounded: where a list is long it shows the busiest items and points you at the
tool. Query the tool; do not read the full generated document into context.

## What this workspace is
{len(services_l)} modules: {", ".join(services_l[:15])}{_more(services_l, 15, "architecture.md")}. {sym} indexed symbols.
Kafka topics: {(str(len(topics_l)) + " — busiest: " + ", ".join(f'`{t}`' for t in top_topics) + _more(topics_l, 15, "message-flows.md, or call message_flow")) if topics_l else "none detected"}.
REST endpoints: {q("SELECT COUNT(*) c FROM http_endpoints")[0]["c"]} (see docs/generated/http-map.md).
Standing decisions: {"; ".join(r[0] for r in q("SELECT id || ' ' || title FROM decisions WHERE valid_until IS NULL ORDER BY decided_at DESC LIMIT 6")) if q("SELECT name FROM sqlite_master WHERE name='decisions'") else "none recorded"} — query via decisions/decision_trace; capture via save_decision.
Database tables: {(str(len(tables_l)) + " — most accessed: " + ", ".join(f'`{t}`' for t in top_tables) + _more(tables_l, 15, "data-map.md, or call db_map")) if tables_l else "none detected"}.

## How to look things up (cheapest first)
1. This pack + `docs/generated/*.md` (architecture, message-flows, data-map) — already summarized.
2. Ariadne MCP tools — `find_symbol`, `file_outline`, `find_callers`, `blast_radius`, `message_flow`, `db_map`, `find_references` (SCIP, compiler-grade).
3. `.github/knowledge/` (Delphi) for module intent and gotchas; `docs/features/` for specs and task state; `docs/constitution.md` for non-negotiables.
4. Source files — only to edit, or when the layers above point you to a specific location.

## High-risk files (largest blast radius — check dependents before touching)
{chr(10).join(f"- `{h['path']}` ({h['n']} dependents)" for h in hot6)}

## Standing rules for implementation work
- Follow the codebase's existing patterns over textbook patterns; when they conflict, match the codebase and note the tension.
- Kafka topic names come from application.yaml or constants — never hardcode a new literal topic.
- Every table change goes through a Liquibase changeset; `db_map` shows the history and will flag drift.
- Run the feature-delivery-loop (test → implement → build → verify → review → document) per increment; update `docs/features/<id>/tasks.md` as you go — PROGRESS.md is generated from it.
"""
write("agent-context.md", md)
ext = DB.parent / "extensions"
if ext.exists():
    import importlib.util
    for f in sorted(ext.glob("doc-*.py")):
        try:
            spec = importlib.util.spec_from_file_location(f.stem.replace("-", "_"), f)
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)
            if hasattr(mod, "generate"):
                mod.generate({"q": q, "write": write, "mm": mm, "svc": svc, "out": OUT})
        except Exception as e:  # noqa: BLE001
            print(f"  ! doc extension {f.name}: {e}")
print("docgen complete.")
