#!/usr/bin/env node
/**
 * AEGIS docgen, deterministic documentation from the Ariadne graph.
 * Zero LLM tokens: everything here is derived mechanically from index.db and
 * docs/features/ artifacts, so it can run on every MR merge.
 *
 * Outputs (docs/generated/):
 *   architecture.md, module/repo dependency map (Mermaid flowchart)
 *   message-flows.md. Kafka topology per topic (Mermaid) + orphan warnings
 *   data-map.md, tables ↔ services ↔ changesets (Mermaid + history)
 *   PROGRESS.md, manager/PO report from docs/features/(spec|tasks|review).md
 *   agent-context.md, compact orientation pack for AI agents (< ~150 lines)
 *
 * Usage: node docgen.mjs   (run from the workspace/repo root, after indexing)
 */
import Database from "better-sqlite3";
import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const DB_PATH = path.join(process.env.ARIADNE_HOME ?? ROOT, ".ariadne", "index.db");
const OUT = path.join(ROOT, "docs", "generated");
const FEATURES = path.join(ROOT, "docs", "features");
const STAMP = `<!-- generated by aegis docgen ${new Date().toISOString()}, do not edit by hand -->`;

// Scale caps: these documents must stay readable AND safe to pull into an agent's
// context. Past these thresholds we emit the signal (warnings) and a pointer to
// the tool, instead of an exhaustive dump nobody can use.
let dcfg = {};
try { dcfg = JSON.parse(fs.readFileSync(path.join(path.dirname(DB_PATH), "config.json"), "utf8")); } catch { /* defaults */ }
const MAX_DIAGRAM_NODES = dcfg.maxDiagramNodes ?? 30;
const MAX_DOC_ITEMS = dcfg.maxDocItems ?? 60;
const capList = (arr, n) => (arr.length > n ? [...arr.slice(0, n), `…and ${arr.length - n} more`] : arr);
const bigDocBanner = (count, what, tool) => count <= MAX_DOC_ITEMS ? "" :
  `> **This file describes ${count} ${what}.** Do not read it whole into an agent's context , \n` +
  `> query \`${tool}\` for the one you need. The warnings below are the part worth reading.\n\n`;

if (!fs.existsSync(DB_PATH)) {
  console.error("Index not found, run the Ariadne indexer first.");
  process.exit(1);
}
fs.mkdirSync(OUT, { recursive: true });
const db = new Database(DB_PATH, { readonly: true });
const q = (sql, ...a) => db.prepare(sql).all(...a);
const svc = (p) => p.split("/")[0];               // repo/module = first path segment
const mmId = (s) => s.replace(/[^\w]/g, "_");     // mermaid-safe id
const write = (name, body) => {
  fs.writeFileSync(path.join(OUT, name), `${STAMP}\n\n${body}`);
  console.log("  +", path.join("docs/generated", name));
};

/* ---------------- architecture.md ---------------- */
{
  const files = q("SELECT path, lang FROM files");
  const services = new Map();
  for (const f of files) {
    const s = services.get(svc(f.path)) ?? { files: 0, langs: {} };
    s.files++; s.langs[f.lang] = (s.langs[f.lang] ?? 0) + 1;
    services.set(svc(f.path), s);
  }
  const edges = q(`SELECT DISTINCT f1.path a, f2.path b FROM edges e
                   JOIN files f1 ON f1.id=e.src JOIN files f2 ON f2.id=e.dst`);
  const svcEdges = new Set();
  for (const e of edges) if (svc(e.a) !== svc(e.b)) svcEdges.add(`${svc(e.a)}-->${svc(e.b)}`);
  const hot = q(`SELECT f.path, COUNT(e.src) n FROM files f JOIN edges e ON e.dst=f.id
                 GROUP BY f.id ORDER BY n DESC LIMIT 10`);
  let md = `# System Architecture (generated)\n\n## Modules\n\n`;
  md += `| Module | Files | Main languages |\n|---|---|---|\n`;
  for (const [name, s] of [...services].sort()) {
    md += `| ${name} | ${s.files} | ${Object.keys(s.langs).sort((a, b) => s.langs[b] - s.langs[a]).slice(0, 3).join(", ")} |\n`;
  }
  const shown = [...services.entries()].sort((a, b) => b[1].files - a[1].files).slice(0, MAX_DIAGRAM_NODES);
  const shownNames = new Set(shown.map(([n]) => n));
  md += `\n## Module dependency map\n\n`;
  if (services.size > MAX_DIAGRAM_NODES) {
    md += `_Showing the ${MAX_DIAGRAM_NODES} largest of ${services.size} modules, a diagram with every node is unreadable. Full list in the table above._\n\n`;
  }
  md += `\`\`\`mermaid\nflowchart LR\n`;
  for (const [name] of shown) md += `  ${mmId(name)}["${name}"]\n`;
  for (const e of svcEdges) {
    const [a, b] = e.split("-->");
    if (!shownNames.has(a) || !shownNames.has(b)) continue;
    md += `  ${mmId(a)} --> ${mmId(b)}\n`;
  }
  md += `\`\`\`\n\n## Most-depended-on files (change with care)\n\n`;
  for (const h of hot) md += `- \`${h.path}\`, ${h.n} dependents\n`;
  write("architecture.md", md);
}

/* ---------------- message-flows.md ---------------- */
{
  const rows = q(`SELECT m.topic, m.direction, f.path, m.line, m.via, m.resolved
                  FROM msg_edges m JOIN files f ON f.id=m.file_id ORDER BY m.topic`);
  const topicCount = new Set(rows.map((r) => r.topic)).size;
  let md = `# Kafka Message Flows (generated)\n\n` + bigDocBanner(topicCount, "topics", "message_flow topic:<name>");
  if (!rows.length) {
    md += "_No Kafka producers/consumers detected._\n";
  } else {
    const topics = {};
    for (const r of rows) (topics[r.topic] ??= []).push(r);
    md += "```mermaid\nflowchart LR\n";
    const seen = new Set();
    for (const [topic, hs] of Object.entries(topics)) {
      const t = `T_${mmId(topic)}`;
      md += `  ${t}(["${topic}"]):::topic\n`;
      for (const h of hs) {
        const s = mmId(svc(h.path));
        if (!seen.has(s)) { md += `  ${s}["${svc(h.path)}"]\n`; seen.add(s); }
        md += h.direction === "produce" ? `  ${s} -->|publish| ${t}\n` : `  ${t} -->|consume| ${s}\n`;
      }
    }
    md += "  classDef topic fill:#1e3a5f,color:#e8c468,stroke:#c9962e\n```\n\n## Per-topic detail\n\n";
    for (const [topic, hs] of Object.entries(topics)) {
      const prod = hs.filter((h) => h.direction === "produce");
      const cons = hs.filter((h) => h.direction === "consume");
      md += `### \`${topic}\`\n`;
      for (const p of prod) md += `- **publish**, \`${p.path}:${p.line}\`${p.via ? ` (via \`${p.via}\`)` : ""}\n`;
      for (const c of cons) md += `- **consume**, \`${c.path}:${c.line}\`${c.via ? ` (via \`${c.via}\`)` : ""}\n`;
      if (prod.length && !cons.length) md += `- ⚠️ produced but no consumer found in the indexed workspace\n`;
      if (cons.length && !prod.length) md += `- ⚠️ consumed but no producer found in the indexed workspace\n`;
      md += "\n";
    }
  }
  write("message-flows.md", md);
}

/* ---------------- data-map.md ---------------- */
{
  const defs = q(`SELECT d.tbl, d.op, f.path, d.line, d.changeset FROM db_defs d
                  LEFT JOIN files f ON f.id=d.file_id ORDER BY d.tbl`);
  const accs = q(`SELECT a.tbl, a.kind, a.mode, f.path, a.line, a.detail FROM db_access a
                  JOIN files f ON f.id=a.file_id ORDER BY a.tbl`);
  const tblCount = new Set([...defs.map((d2) => d2.tbl), ...accs.map((a) => a.tbl)]).size;
  let md = `# Data Map, tables, services, changesets (generated)\n\n` + bigDocBanner(tblCount, "tables", "db_map table:<name>");
  if (!defs.length && !accs.length) {
    md += "_No Liquibase changelogs or DB access detected._\n";
  } else {
    const tables = new Map();
    for (const d of defs) (tables.get(d.tbl) ?? tables.set(d.tbl, { defs: [], accs: [] }).get(d.tbl)).defs.push(d);
    for (const a of accs) (tables.get(a.tbl) ?? tables.set(a.tbl, { defs: [], accs: [] }).get(a.tbl)).accs.push(a);
    md += "```mermaid\nflowchart LR\n";
    const seenSvc = new Set();
    for (const [tbl, t] of tables) {
      md += `  DB_${mmId(tbl)}[("${tbl}")]:::tbl\n`;
      for (const a of t.accs) {
        const s = mmId(svc(a.path));
        if (!seenSvc.has(s)) { md += `  ${s}["${svc(a.path)}"]\n`; seenSvc.add(s); }
        md += `  ${s} -->|${a.mode}| DB_${mmId(tbl)}\n`;
      }
    }
    md += "  classDef tbl fill:#0d1b2e,color:#7dd3fc,stroke:#38bdf8\n```\n\n## Per-table detail\n\n";
    for (const [tbl, t] of [...tables].sort()) {
      md += `### \`${tbl}\`\n`;
      if (t.defs.length) {
        md += `**Schema history:** ` + t.defs.map((d) => `${d.op}${d.changeset ? ` [${d.changeset}]` : ""}`).join(" → ") + `\n`;
        md += t.defs.map((d) => `- ${d.op} @ \`${d.path}:${d.line}\``).join("\n") + "\n";
      } else {
        md += `- ⚠️ **DRIFT**, accessed by code but no Liquibase changeset defines it in the indexed workspace\n`;
      }
      for (const a of t.accs) md += `- ${a.kind} [${a.mode}], \`${a.path}:${a.line}\` (${a.detail})\n`;
      if (t.defs.length && !t.accs.length) md += `- ⚠️ defined in changelog but no code access found\n`;
      md += "\n";
    }
  }
  write("data-map.md", md);
}

/* ---------------- http-map.md ---------------- */
{
  const eps = q(`SELECT e.method, e.path, e.norm, f.path fp, e.line FROM http_endpoints e JOIN files f ON f.id=e.file_id ORDER BY e.norm`);
  const calls = q(`SELECT c.method, c.path, c.norm, f.path fp, c.line, c.client FROM http_calls c JOIN files f ON f.id=c.file_id`);
  let md = `# HTTP Seam, endpoints and callers (generated)\n\n` + bigDocBanner(eps.length, "endpoints", "http_map path:<fragment>");
  if (!eps.length && !calls.length) {
    md += "_No REST endpoints or HTTP clients detected._\n";
  } else {
    const { pathsMatch } = await import("./http.mjs");
    md += "```mermaid\nflowchart LR\n";
    const seen = new Set();
    const matched = new Set();
    for (const e of eps) {
      const es = mmId(svc(e.fp)); if (!seen.has(es)) { md += `  ${es}["${svc(e.fp)}"]\n`; seen.add(es); }
      for (let i = 0; i < calls.length; i++) {
        const c = calls[i];
        if (c.method === e.method && pathsMatch(c.norm, e.norm)) {
          matched.add(i);
          const cs = mmId(svc(c.fp)); if (!seen.has(cs)) { md += `  ${cs}["${svc(c.fp)}"]\n`; seen.add(cs); }
          md += `  ${cs} -->|"${e.method} ${e.norm}"| ${es}\n`;
        }
      }
    }
    md += "```\n\n## Endpoints\n\n";
    for (const e of eps) {
      const callers = calls.filter((c) => c.method === e.method && pathsMatch(c.norm, e.norm));
      md += `- **${e.method} ${e.path}**, \`${e.fp}:${e.line}\`` + (callers.length
        ? "\n" + callers.map((c) => `  - caller: \`${c.fp}:${c.line}\` (${c.client})`).join("\n")
        : ", ⚠️ no caller found in the indexed workspace") + "\n";
    }
    const un = calls.filter((_, i) => !matched.has(i));
    if (un.length) {
      md += "\n## Unmatched outbound calls (external APIs or dynamic paths)\n\n";
      md += un.map((c) => `- ${c.method} ${c.path}, \`${c.fp}:${c.line}\` (${c.client})`).join("\n") + "\n";
    }
  }
  write("http-map.md", md);
}

/* ---------------- decisions.md ---------------- */
{
  const has = q("SELECT name FROM sqlite_master WHERE name='decisions'").length;
  const rows = has ? q("SELECT * FROM decisions ORDER BY decided_at DESC") : [];
  let md = `# Decision Memory. Mnemosyne (generated)\n\n`;
  if (!rows.length) md += "_No ADR decisions found. Capture one in chat via the save_decision tool, or add docs/adr/ADR-NNN-*.md files._\n";
  else {
    const active = rows.filter((r) => !r.valid_until);
    md += `## Active decisions (${active.length})\n\n| ID | Title | Decided | Governs |\n|---|---|---|---|\n`;
    for (const r of active) {
      const g = q("SELECT kind, target FROM decision_links WHERE decision_id=?", r.id);
      md += `| ${r.id} | ${r.title} | ${r.decided_at ?? "?"} | ${g.map((l) => l.kind + ":" + l.target).join(", ") || ", "} |\n`;
    }
    const sup = rows.filter((r) => r.valid_until);
    if (sup.length) {
      md += `\n## Superseded (history preserved)\n\n`;
      for (const r of sup) md += `- ~~${r.id}: ${r.title}~~, valid ${r.decided_at} → ${r.valid_until}, superseded by **${r.superseded_by}**\n`;
    }
    md += `\n_Query in chat: decisions / decision_trace; time-travel with as_of. Capture new ones with save_decision._\n`;
  }
  write("decisions.md", md);
}

/* ---------------- PROGRESS.md ---------------- */
{
  let md = `# Progress Report (generated)\n\n`;
  const features = fs.existsSync(FEATURES)
    ? fs.readdirSync(FEATURES).filter((d) => fs.statSync(path.join(FEATURES, d)).isDirectory()).sort()
    : [];
  if (!features.length) {
    md += "_No feature artifacts under docs/features/ yet. Features managed via the spec-driven-artifacts skill will appear here automatically._\n";
  } else {
    let gDone = 0, gTodo = 0, gProg = 0, gBlocked = 0;
    const rowsOut = [];
    for (const f of features) {
      const read = (n) => { try { return fs.readFileSync(path.join(FEATURES, f, n), "utf8"); } catch { return ""; } };
      const tasks = read("tasks.md");
      const done = (tasks.match(/^- \[x\]/gim) ?? []).length;
      const prog = (tasks.match(/^- \[~\]/gim) ?? []).length;
      const blocked = (tasks.match(/^- \[!\]/gim) ?? []).length;
      const todo = (tasks.match(/^- \[ \]/gim) ?? []).length;
      const total = done + prog + blocked + todo;
      const frs = (read("spec.md").match(/^\s*-\s*\*\*FR-/gim) ?? []).length;
      const clar = (read("spec.md").match(/NEEDS CLARIFICATION/g) ?? []).length;
      const verdicts = [...read("review.md").matchAll(/\*\*Verdict\*\*:\s*([A-Z-]+)/g)].map((m) => m[1]);
      const pct = total ? Math.round((done / total) * 100) : 0;
      gDone += done; gTodo += todo; gProg += prog; gBlocked += blocked;
      const status = blocked ? "🔴 blocked" : pct === 100 ? "✅ done" : prog || done ? "🟡 in progress" : "⚪ not started";
      rowsOut.push(`| ${f} | ${status} | ${pct}% | ${done}/${total} | ${frs} | ${clar || ", "} | ${verdicts.at(-1) ?? ", "} |`);
    }
    const gTotal = gDone + gTodo + gProg + gBlocked;
    md += `**Overall: ${gTotal ? Math.round((gDone / gTotal) * 100) : 0}% of tracked tasks complete** (${gDone} done, ${gProg} in progress, ${gBlocked} blocked, ${gTodo} to do)\n\n`;
    md += "```mermaid\npie showData\n  title Task status across all features\n";
    md += `  "Done" : ${gDone}\n  "In progress" : ${gProg}\n  "Blocked" : ${gBlocked}\n  "To do" : ${gTodo}\n\`\`\`\n\n`;
    md += `| Feature | Status | % | Tasks | FRs | Open clarifications | Last review |\n|---|---|---|---|---|---|---|\n`;
    md += rowsOut.join("\n") + "\n\n";
    md += `_Counts derive from docs/features/*/tasks.md checkboxes, spec.md FR-### lines, and review.md verdicts. Keep those artifacts current (the delivery loop does this) and this report stays true with zero manual effort._\n`;
  }
  write("PROGRESS.md", md);
}

/* ---------------- agent-context.md ---------------- */
{
  const files = q("SELECT path, lang FROM files");
  const services = [...new Set(files.map((f) => svc(f.path)))].sort();
  const topics = q("SELECT DISTINCT topic FROM msg_edges ORDER BY topic").map((r) => r.topic);
  const tables = q("SELECT DISTINCT tbl FROM db_defs UNION SELECT DISTINCT tbl FROM db_access ORDER BY 1").map((r) => r.tbl);
  const hot = q(`SELECT f.path, COUNT(e.src) n FROM files f JOIN edges e ON e.dst=f.id
                 GROUP BY f.id ORDER BY n DESC LIMIT 6`);
  const counts = q("SELECT COUNT(*) c FROM symbols")[0].c;
  const topTopics = q(`SELECT topic, COUNT(*) n FROM msg_edges GROUP BY topic ORDER BY n DESC LIMIT 15`).map((r) => r.topic);
  const topTables = q(`SELECT tbl, COUNT(*) n FROM db_access GROUP BY tbl ORDER BY n DESC LIMIT 15`).map((r) => r.tbl);
  const topMods = [...services].slice(0, 15);
  const more = (all, shownN, doc) => all.length > shownN ? ` (+${all.length - shownN} more, see ${doc})` : "";
  let md = `# Agent Context Pack (generated, read this FIRST, then use Ariadne tools)\n
This file plus one or two tool calls should orient you completely. Do not
re-derive anything listed here by reading source files. This pack is deliberately
bounded: where a list is long, it shows the busiest items and points you at the
tool. Query the tool; do not read the full generated document into context.\n
## What this workspace is
${services.length} modules${services.length ? ": " + topMods.join(", ") + more(services, 15, "architecture.md") : ""}. ${counts} indexed symbols.
Kafka topics: ${topics.length ? `${topics.length}, busiest: ` + topTopics.map((t) => `\`${t}\``).join(", ") + more(topics, 15, "message-flows.md, or call message_flow") : "none detected"}.
REST endpoints: ${q("SELECT COUNT(*) c FROM http_endpoints")[0].c} (see docs/generated/http-map.md).
Standing decisions: ${(q("SELECT name FROM sqlite_master WHERE name='decisions'").length ? q("SELECT id || ' ' || title t FROM decisions WHERE valid_until IS NULL ORDER BY decided_at DESC LIMIT 6") : []).map((r) => r.t).join("; ") || "none recorded"}, query via decisions/decision_trace; capture via save_decision.
Database tables: ${tables.length ? `${tables.length}, most accessed: ` + topTables.map((t) => `\`${t}\``).join(", ") + more(tables, 15, "data-map.md, or call db_map") : "none detected"}.\n
## How to look things up (cheapest first)
1. This pack + \`docs/generated/*.md\` (architecture, message-flows, data-map), already summarized.
2. Ariadne MCP tools, \`find_symbol\`, \`file_outline\`, \`find_callers\`, \`blast_radius\`, \`message_flow\`, \`db_map\`, \`find_references\` (SCIP, compiler-grade).
3. \`.github/knowledge/\` (Delphi) for module intent and gotchas; \`docs/features/\` for specs and task state; \`docs/constitution.md\` for non-negotiables.
4. Source files, only to edit, or when the layers above point you to a specific location.\n
## High-risk files (largest blast radius, check dependents before touching)
${hot.map((h) => `- \`${h.path}\` (${h.n} dependents)`).join("\n")}\n
## Standing rules for implementation work
- Follow the codebase's existing patterns over textbook patterns; when they conflict, match the codebase and note the tension.
- Kafka topic names come from application.yaml or constants, never hardcode a new literal topic.
- Every table change goes through a Liquibase changeset; \`db_map\` shows the history and will flag drift.
- Run the feature-delivery-loop (test → implement → build → verify → review → document) per increment; update \`docs/features/<id>/tasks.md\` as you go. PROGRESS.md is generated from it.
`;
  write("agent-context.md", md);
}

/* ---------------- plugin generators: .ariadne/extensions/doc-*.mjs export generate(ctx) ---------------- */
{
  const dir = path.join(path.dirname(DB_PATH), "extensions");
  if (fs.existsSync(dir)) {
    for (const f of fs.readdirSync(dir).filter((x) => /^doc-.*\.mjs$/.test(x))) {
      try {
        const mod = await import("file://" + path.join(dir, f));
        if (typeof mod.generate === "function") await mod.generate({ q, write, mmId, svc, OUT });
      } catch (e) { console.error(`  ! doc extension ${f}: ${e.message}`); }
    }
  }
}
console.log("docgen complete.");
